// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BucketService is the Wails-bound facade for KeyValue / Object Store
 * management (spec §6.8/§6.9). Settings are read per call; every method
 * returns a CallResult-embedding struct, never a bare error, so the frontend
 * can branch on error_code (spec §8.5.2).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as connections$0 from "../connections/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CompactKvBucket purges delete markers together with the history they
 * gate. DeleteMarkersOlderThan(-1) is the unconditional variant: a zero
 * value would mean nats.go's 30-minute default threshold
 * (kv.go kvDefaultPurgeDeletesMarkerThreshold), NOT delete-all — only the
 * negative duration skips the age filter and purges every marker.
 */
export function CompactKvBucket(name: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(3066257731, name).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateKvBucket validates the form and creates the bucket. nats-server
 * treats a duplicate CREATE carrying an identical config as idempotent
 * success — ErrBucketExists (→ conflict) only surfaces for a differing
 * config, which is what the UI's duplicate banner is for.
 */
export function CreateKvBucket(form: $models.KvBucketForm): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(2741664732, form).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateKvWatch 订阅 KV 桶：keys 空 = 整桶（WatchAll），否则经 ValidateWatchFilter
 * 的过滤串（Watch）。事件 kv:watch：初始逐键 + key="" sentinel（初始快照完成），
 * 随后增量；值含 payload（不用 UpdatesOnly）。桶句柄解析走请求超时，订阅 ctx 用
 * Background 派生的长生命周期 cancel ctx（绝不 s.timeout()）。
 */
export function CreateKvWatch(bucket: string, keys: string): $CancellablePromise<$models.CreateWatchResult> {
    return $Call.ByID(112755009, bucket, keys).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateObjBucket validates the form and creates the bucket. nats-server
 * treats a duplicate CREATE carrying an identical config as idempotent
 * success — ErrBucketExists (→ conflict) only surfaces for a differing
 * config, same as the KV half.
 */
export function CreateObjBucket(form: $models.ObjBucketForm): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(2824647206, form).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateObjWatch 订阅对象桶（Task 5 UI 消费）：事件 obj:watch，初始全量 +
 * name="" sentinel，随后增量。ObjectInfo → ObjWatchEvent（ModTime → 毫秒 epoch）。
 */
export function CreateObjWatch(bucket: string): $CancellablePromise<$models.CreateWatchResult> {
    return $Call.ByID(2286577955, bucket).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteKey 两模式删除：delete（打删除标记，历史保留，可 revert）/ purge
 * （打标记并移除此前的全部修订，§6.8 彻底清除；UI 层负责二级确认）。
 */
export function DeleteKey(bucket: string, key: string, mode: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(2757858687, bucket, key, mode).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteKvBucket removes the bucket and its data (二级确认在 UI 层).
 */
export function DeleteKvBucket(name: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(1232063863, name).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteObjBucket removes the bucket and its data (二级确认在 UI 层).
 */
export function DeleteObjBucket(name: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(4035944791, name).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteObject 删除（打删除标记 + 清分片，一级确认在 UI 层）：对象**不存在** →
 * not_found；对象**已删除** → Ok（nats.go Delete 文档语义 "If the object is
 * already deleted, no error will be returned"——重删幂等，测试钉住）。
 */
export function DeleteObject(bucket: string, name: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(1122466103, bucket, name).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DownloadObject 下载桶内对象到目录（§6.9）：磁盘预检（free>0 且 < info.Size
 * 才拒绝——0 = 未知平台/查询失败，绝不阻止）→ os.Get（info 返回时即就绪，取
 * bytes_total/digest）→ 覆盖写（已存在先删，Windows rename 语义）→ io.Copy
 * （countingWriter 节流 running + TeeReader 进 sha256）→ 摘要复核。摘要不匹配
 * （含 nats.go Read 在 EOF 的内建 ErrDigestMismatch——tee 是第二道双保险）→
 * phase=incomplete + error「digest mismatch」，文件保留供人工比对；匹配 →
 * complete + digest_match=true。传输 ctx 不设超时（nats.go Read 在无 deadline
 * ctx 下用 per-read 默认 API 超时，大文件不受绝对期限截断），watchdog 兜断连
 * （取消 ctx → Read 返回错误 → incomplete）。
 */
export function DownloadObject(bucket: string, name: string, dir: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(1616482772, bucket, name, dir).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetKeyHistory 返回键的全量修订历史（含值，升序——流序列即历史顺序，删除
 * 标记也在其中，§6.8「历史可查」）。键不存在 → not_found。
 */
export function GetKeyHistory(bucket: string, key: string): $CancellablePromise<$models.GetKeyHistoryResult> {
    return $Call.ByID(192687300, bucket, key).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetKeyValues 批量补齐键值：sync.WaitGroup + 预分配索引写入（out[i] 只被
 * 唯一 goroutine 写，无锁无竞争），并发上限 8（不用 errgroup：golang.org/x/sync
 * 不进依赖树，Global 12）。ErrKeyNotFound（含已删除键——kv.Get 把 ErrKeyDeleted
 * 归一为 ErrKeyNotFound）→ 该键 NotFound=true，不拖垮整批；其余错误取首错
 * 分类后整批失败。
 */
export function GetKeyValues(bucket: string, keys: string[]): $CancellablePromise<$models.GetKeyValuesResult> {
    return $Call.ByID(4169159946, bucket, keys).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetKvBucketDetail loads one KV bucket and echoes the editable form.
 * KeyValueStatus has no Created field (verified against nats.go v1.53.1 —
 * the interface exposes exactly 10 methods), so CreatedMs stays 0; the
 * frontend does not display bucket creation time.
 */
export function GetKvBucketDetail(name: string): $CancellablePromise<$models.BucketDetailResult> {
    return $Call.ByID(2983820083, name).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetObjBucketDetail loads one object bucket: editable-form echo + Sealed.
 * ObjectStoreStatus 的接口没有 MaxBytes 取值器，而 prepareObjectStoreConfig 会
 * 把 MaxBytes 0 归一为 -1（无限制）——若详情回显落 0，用户仅改描述提交就会把
 * 已配置的配额静默重置为无限制。ObjectBucketStatus（nats.go v1.53.1 中 Status
 * 的唯一具体实现）额外导出 StreamInfo()，用它补齐 MaxBytes；断言失败（未来
 * 版本变更）时保持 0 并由前端表单按「不设置」处理。
 */
export function GetObjBucketDetail(name: string): $CancellablePromise<$models.ObjBucketDetailResult> {
    return $Call.ByID(1408689397, name).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListKeys 收集桶内全部键的最新元数据。MetaOnly 只取 meta 不取值（值由
 * GetKeyValues 批量补齐）；不用 UpdatesOnly——初始快照正是列表要的数据；
 * 不用 IgnoreDeletes——删除/清除标记键仍出现在列表（Operation=delete/purge，
 * §6.8「历史可查」浏览语义）。nil 哨兵表示初始快照结束，随即 Stop 释放
 * 服务端有序消费者。
 */
export function ListKeys(bucket: string): $CancellablePromise<$models.ListKeysResult> {
    return $Call.ByID(1128341107, bucket).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListKvBuckets lists the KV half of the bucket surface via the
 * KeyValueStores lister; ObjBuckets stays nil (Task 5 fills the object
 * half — the frontend pages each call their own method against the shared
 * result shape). UnavailableReason 仅描述 JS 层不可用成因（no_responders/
 * timeout/server）；not_connected 不属于指引面板语义（前端按连接状态整体
 * gate），置空——对齐 jsadmin.ListStreams。
 */
export function ListKvBuckets(): $CancellablePromise<$models.ListBucketsResult> {
    return $Call.ByID(1741966469).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ListObjBuckets lists the object half via the ObjectStores lister, filling the
 * ObjBuckets half of the shared ListBucketsResult (the frontend pages each call
 * their own method against the same result shape as ListKvBuckets).
 * UnavailableReason 仅描述 JS 层不可用成因（no_responders/timeout/server），
 * not_connected 不属于指引面板语义——对齐 ListKvBuckets/jsadmin.ListStreams。
 */
export function ListObjBuckets(): $CancellablePromise<$models.ListBucketsResult> {
    return $Call.ByID(3874068599).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ListObjects 收集桶内全部对象（含已删除）。**必须带 ListObjectsShowDeleted**：
 * 默认 List 过滤已删除对象（nats.go object.go List→IgnoreDeletes），「已删除」
 * 徽标（§6.9 浏览语义）将永不出现。空桶/无对象 → ErrNoObjectsFound 吞掉返回
 * 空数组（非 nil，前端 .length 语义）。
 */
export function ListObjects(bucket: string): $CancellablePromise<$models.ListObjectsResult> {
    return $Call.ByID(367096585, bucket).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * NotifyConnState 是 main.go 的 conn:state side-band（对齐 messaging
 * SessionManager 惯例）：state != connected → 全部 watcher Stop + 注册表清空 +
 * WARN 计数。订阅随连接消亡本就会失效，这里显式回收注册表与 goroutine。通知
 * 路径非阻塞（stopAll 不持锁执行 stop），可安全从 Manager 的 emit 路径调用。
 */
export function NotifyConnState(ev: connections$0.StateEvent): $CancellablePromise<void> {
    return $Call.ByID(1236430137, ev);
}

/**
 * OpenInFileManager 在资源管理器中定位并选中 path（§6.9「打开所在目录入口」）：
 * explorer /select——零新依赖。explorer 进程异步启动，失败仅为本进程侧错误。
 */
export function OpenInFileManager(path: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(1826089049, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PickDownloadDirectory opens the native directory chooser (对齐
 * PickBackupDirectory). "" means the user cancelled.
 */
export function PickDownloadDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1895653381);
}

/**
 * PickUploadFiles opens the native multi-select file chooser (M3
 * PickBackupDirectory 同款链). Returns the selected paths; cancel/err → empty
 * slice (no error surfaced to the UI, 同 PickBackupDirectory 语义).
 */
export function PickUploadFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(1130000770).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * PutKey 三语义写入：put（无条件）/ create（键不存在才写，ErrKeyExists →
 * conflict，服务器原文前置 + 「可改用 put 或查看现有值」指引）/ update（CAS：
 * expectedRevision 不符 → conflict，并回读当前修订填 CurrentRevision——kv.Get
 * 失败置 0）。值经 base64 解码后过 8MB 上限校验；键名走 ValidateKeyName
 * （'/' 合法，natscli 互操作）。
 */
export function PutKey(bucket: string, key: string, payloadB64: string, mode: string, expectedRevision: number): $CancellablePromise<$models.PutKeyResult> {
    return $Call.ByID(2473772511, bucket, key, payloadB64, mode, expectedRevision).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * RenameObject 改名。注意 nats.go 的 UpdateMeta 以传入 meta **整体覆盖**元数据
 * （Description/Headers/Metadata 直接取传入值，零值即清空）——先 GetInfo 回填
 * 旧值再改名，避免外部创建的带描述/元数据对象在改名时被静默清空（Task 5 审查
 * 裁定）。源对象不存在/已删除 → not_found（nats.go 把不存在的 GetInfo 归一为
 * ErrUpdateMetaDeleted，服务层还原 not_found）；新名已被占用 → conflict。
 */
export function RenameObject(bucket: string, name: string, newName: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(396883350, bucket, name, newName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RevertKey 删除态感知回退（F-09）：历史升序；最新条目为 delete/purge 标记 →
 * 目标 = 最后一个有效修订本身（恢复最后有效值）；最新条目有效 → 目标 = 倒数
 * 第二个有效修订（活键回退一步，跳过历史中的标记）。有效修订不足（活键仅
 * 1 修订，或删除态下无更早有效修订——如 purge 后）→ validation + ErrNoHistory。
 * 回退 = 以目标值 kv.Put 产生新修订（流序列不回滚）。
 */
export function RevertKey(bucket: string, key: string): $CancellablePromise<$models.PutKeyResult> {
    return $Call.ByID(2097795796, bucket, key).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * SealObjBucket seals the bucket: no further writes (UI 按 sealed 状态禁用
 * 上传/编辑，服务器错误仍原文透传，§6.9 异常 3)。Seal 幂等。
 */
export function SealObjBucket(name: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(4043992797, name).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StopWatch 关停单个 watcher：close done + stops（wcancel + watcher.Stop）+
 * 注册表删除。未知 id → not_found。
 */
export function StopWatch(watchId: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(2078434282, watchId).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateKvBucket validates the form and patches the bucket. History can only
 * grow on the server (shrink is rejected as a 400 → validation, 表单内联).
 */
export function UpdateKvBucket(form: $models.KvBucketForm): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(3480026917, form).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateObjBucket validates the form and patches the bucket (description /
 * max_bytes / replicas). Sealed 桶的更新被服务器以 400 拒绝 → validation 原文
 * 透传；缺失桶 ErrBucketNotFound → not_found。
 */
export function UpdateObjBucket(form: $models.ObjBucketForm): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(3963967693, form).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UploadObject 上传本地文件到对象桶（§6.9）：阻塞调用 + obj:transfer 事件。
 * CompareAndSwap 门在任何 IO 之前；bytes_total = os.stat 的 size；rename 为空
 * 时取 filepath.Base(path)。传输 ctx 不设超时（nats.go Put 在无 deadline ctx 下
 * 用 per-publish 默认超时，大文件不受绝对期限截断），watchdog 兜断连。失败路径
 * 先发 incomplete 再返回分类错误，成功才以 complete 收尾（bytes_done == bytes_total）。
 */
export function UploadObject(bucket: string, path: string, rename: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(4217665173, bucket, path, rename).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CallResult.createFrom;
const $$createType1 = $models.CreateWatchResult.createFrom;
const $$createType2 = $models.GetKeyHistoryResult.createFrom;
const $$createType3 = $models.GetKeyValuesResult.createFrom;
const $$createType4 = $models.BucketDetailResult.createFrom;
const $$createType5 = $models.ObjBucketDetailResult.createFrom;
const $$createType6 = $models.ListKeysResult.createFrom;
const $$createType7 = $models.ListBucketsResult.createFrom;
const $$createType8 = $models.ListObjectsResult.createFrom;
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = $models.PutKeyResult.createFrom;
