// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as BucketService from "./bucketservice.js";
export {
    BucketService
};

export {
    BucketDetailResult,
    CallResult,
    CreateWatchResult,
    GetKeyHistoryResult,
    GetKeyValuesResult,
    KeyHistoryEntry,
    KeyMeta,
    KeyValueOut,
    KvBucketForm,
    KvBucketSummary,
    ListBucketsResult,
    ListKeysResult,
    ListObjectsResult,
    ObjBucketDetailResult,
    ObjBucketForm,
    ObjBucketSummary,
    ObjectOut,
    PutKeyResult
} from "./models.js";
