// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BucketDetailResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;

    /**
     * KV 详情（GetKvBucketDetail）
     */
    "form": KvBucketForm;
    "created_ms": number;

    /** Creates a new BucketDetailResult instance. */
    constructor($$source: Partial<BucketDetailResult> = {}) {
        if (!("error_code" in $$source)) {
            this["error_code"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("form" in $$source)) {
            this["form"] = (new KvBucketForm());
        }
        if (!("created_ms" in $$source)) {
            this["created_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BucketDetailResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BucketDetailResult {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("form" in $$parsedSource) {
            $$parsedSource["form"] = $$createField2_0($$parsedSource["form"]);
        }
        return new BucketDetailResult($$parsedSource as Partial<BucketDetailResult>);
    }
}

/**
 * CallResult is embedded in every bound-call result; Ok is true iff
 * ErrorCode is empty (same shape as jsadmin, re-declared in this package).
 */
export class CallResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;

    /** Creates a new CallResult instance. */
    constructor($$source: Partial<CallResult> = {}) {
        if (!("error_code" in $$source)) {
            this["error_code"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CallResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CallResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CallResult($$parsedSource as Partial<CallResult>);
    }
}

/**
 * KvBucketForm: 数值字段 0 = 不设置（服务器默认），-1 = 无限制（ttl_seconds 仅 ≥0）。
 */
export class KvBucketForm {
    "name": string;
    "description": string;

    /**
     * 0 = 服务器默认(1)，1–64
     */
    "history": number;

    /**
     * ≥0，0 = 不过期
     */
    "ttl_seconds": number;

    /**
     * ≥-1
     */
    "max_bytes": number;

    /**
     * 1–5，0 视为 1
     */
    "replicas": number;

    /**
     * ≥-1
     */
    "max_value_size": number;

    /** Creates a new KvBucketForm instance. */
    constructor($$source: Partial<KvBucketForm> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("history" in $$source)) {
            this["history"] = 0;
        }
        if (!("ttl_seconds" in $$source)) {
            this["ttl_seconds"] = 0;
        }
        if (!("max_bytes" in $$source)) {
            this["max_bytes"] = 0;
        }
        if (!("replicas" in $$source)) {
            this["replicas"] = 0;
        }
        if (!("max_value_size" in $$source)) {
            this["max_value_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KvBucketForm instance from a string or object.
     */
    static createFrom($$source: any = {}): KvBucketForm {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KvBucketForm($$parsedSource as Partial<KvBucketForm>);
    }
}

export class KvBucketSummary {
    "name": string;
    "description": string;
    "values": number;
    "history": number;
    "ttl_seconds": number;
    "bytes": number;
    "max_bytes": number;
    "replicas": number;
    "is_compressed": boolean;

    /** Creates a new KvBucketSummary instance. */
    constructor($$source: Partial<KvBucketSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("values" in $$source)) {
            this["values"] = 0;
        }
        if (!("history" in $$source)) {
            this["history"] = 0;
        }
        if (!("ttl_seconds" in $$source)) {
            this["ttl_seconds"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("max_bytes" in $$source)) {
            this["max_bytes"] = 0;
        }
        if (!("replicas" in $$source)) {
            this["replicas"] = 0;
        }
        if (!("is_compressed" in $$source)) {
            this["is_compressed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KvBucketSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): KvBucketSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KvBucketSummary($$parsedSource as Partial<KvBucketSummary>);
    }
}

export class ListBucketsResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;
    "kv_buckets": KvBucketSummary[];
    "obj_buckets": ObjBucketSummary[];
    "unavailable_reason": string;

    /** Creates a new ListBucketsResult instance. */
    constructor($$source: Partial<ListBucketsResult> = {}) {
        if (!("error_code" in $$source)) {
            this["error_code"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("kv_buckets" in $$source)) {
            this["kv_buckets"] = [];
        }
        if (!("obj_buckets" in $$source)) {
            this["obj_buckets"] = [];
        }
        if (!("unavailable_reason" in $$source)) {
            this["unavailable_reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListBucketsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ListBucketsResult {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("kv_buckets" in $$parsedSource) {
            $$parsedSource["kv_buckets"] = $$createField2_0($$parsedSource["kv_buckets"]);
        }
        if ("obj_buckets" in $$parsedSource) {
            $$parsedSource["obj_buckets"] = $$createField3_0($$parsedSource["obj_buckets"]);
        }
        return new ListBucketsResult($$parsedSource as Partial<ListBucketsResult>);
    }
}

export class ObjBucketSummary {
    "name": string;
    "description": string;
    "size": number;
    "sealed": boolean;
    "replicas": number;
    "ttl_seconds": number;

    /** Creates a new ObjBucketSummary instance. */
    constructor($$source: Partial<ObjBucketSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("sealed" in $$source)) {
            this["sealed"] = false;
        }
        if (!("replicas" in $$source)) {
            this["replicas"] = 0;
        }
        if (!("ttl_seconds" in $$source)) {
            this["ttl_seconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObjBucketSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ObjBucketSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ObjBucketSummary($$parsedSource as Partial<ObjBucketSummary>);
    }
}

// Private type creation functions
const $$createType0 = KvBucketForm.createFrom;
const $$createType1 = KvBucketSummary.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ObjBucketSummary.createFrom;
const $$createType4 = $Create.Array($$createType3);
