// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface BucketDetailResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;

    /**
     * KV 详情（GetKvBucketDetail）
     */
    "form": KvBucketForm;
    "created_ms": number;
}

/**
 * CallResult is embedded in every bound-call result; Ok is true iff
 * ErrorCode is empty (same shape as jsadmin, re-declared in this package).
 */
export interface CallResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;
}

/**
 * CreateWatchResult：单结构体返回（Wails 多返回值序列化为 JSON 数组，破坏前端
 * 既有 CallResult 消费模式）；WatchId 为注册表内递增的数字串。
 */
export interface CreateWatchResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;
    "watch_id": string;
}

export interface GetKeyHistoryResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;
    "entries": KeyHistoryEntry[] | null;
}

export interface GetKeyValuesResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;
    "values": KeyValueOut[] | null;
}

export interface KeyHistoryEntry {
    "revision": number;
    "payload_b64": string;
    "payload_size": number;
    "is_utf8": boolean;
    "created_ms": number;
    "operation": string;
}

/**
 * KeyMeta: 键名+元数据（列表用，值另行批量补齐）。
 */
export interface KeyMeta {
    "key": string;
    "revision": number;
    "created_ms": number;

    /**
     * put | delete | purge
     */
    "operation": string;
}

/**
 * KeyValueOut: 批量值补齐的单键结果；缺失键 NotFound=true（键在列表后被删）。
 */
export interface KeyValueOut {
    "key": string;
    "revision": number;
    "payload_b64": string;
    "payload_size": number;
    "is_utf8": boolean;
    "created_ms": number;
    "operation": string;
    "not_found": boolean;
}

/**
 * KvBucketForm: 数值字段 0 = 不设置（服务器默认），-1 = 无限制（ttl_seconds 仅 ≥0）。
 */
export interface KvBucketForm {
    "name": string;
    "description": string;

    /**
     * 0 = 服务器默认(1)，1–64
     */
    "history": number;

    /**
     * ≥0，0 = 不过期
     */
    "ttl_seconds": number;

    /**
     * ≥-1
     */
    "max_bytes": number;

    /**
     * 1–5，0 视为 1
     */
    "replicas": number;

    /**
     * ≥-1
     */
    "max_value_size": number;
}

export interface KvBucketSummary {
    "name": string;
    "description": string;
    "values": number;
    "history": number;
    "ttl_seconds": number;
    "bytes": number;
    "max_bytes": number;
    "replicas": number;
    "is_compressed": boolean;
}

export interface ListBucketsResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;
    "kv_buckets": KvBucketSummary[] | null;
    "obj_buckets": ObjBucketSummary[] | null;
    "unavailable_reason": string;
}

export interface ListKeysResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;
    "keys": KeyMeta[] | null;

    /**
     * 已读键数（MetaOnly 无法预知真实总数；截断时 = 已读键数）
     */
    "total": number;

    /**
     * 超过 kvListKeysCap 封顶，未列出的键存在
     */
    "truncated": boolean;
}

export interface ListObjectsResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;
    "objects": ObjectOut[] | null;
}

/**
 * ObjBucketDetailResult: 对象桶详情（GetObjBucketDetail）——表单回显 + 封存
 * 状态（封存桶前端禁用上传/编辑，§6.9 异常 3）。
 */
export interface ObjBucketDetailResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;
    "form": ObjBucketForm;
    "sealed": boolean;
}

export interface ObjBucketForm {
    "name": string;
    "description": string;

    /**
     * ≥-1
     */
    "max_bytes": number;

    /**
     * 1–5
     */
    "replicas": number;
}

export interface ObjBucketSummary {
    "name": string;
    "description": string;
    "size": number;
    "sealed": boolean;
    "replicas": number;
    "ttl_seconds": number;
}

export interface ObjectOut {
    "name": string;
    "size": number;
    "chunks": number;
    "digest": string;
    "mod_time_ms": number;
    "deleted": boolean;
}

/**
 * PutKeyResult: revision 为新修订号；冲突时 CurrentRevision 填当前修订（§6.8 异常 2）。
 */
export interface PutKeyResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;
    "revision": number;
    "current_revision": number;
}
