// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AccountListResult {
    "error_code": string;
    "error": string;
    "accounts": AccountRow[];

    /** Creates a new AccountListResult instance. */
    constructor($$source: Partial<AccountListResult> = {}) {
        if (!("error_code" in $$source)) {
            this["error_code"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("accounts" in $$source)) {
            this["accounts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AccountListResult {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("accounts" in $$parsedSource) {
            $$parsedSource["accounts"] = $$createField2_0($$parsedSource["accounts"]);
        }
        return new AccountListResult($$parsedSource as Partial<AccountListResult>);
    }
}

/**
 * AccountRow：账户信息与统计（serverdata.CollectAccounts 聚合结果）。
 */
export class AccountRow {
    "name": string;
    "id": string;
    "streams": number;
    "consumers": number;
    "memory_bytes": number;
    "store_bytes": number;
    "reserved_memory_bytes": number;
    "reserved_store_bytes": number;
    "stream_names": string[];

    /** Creates a new AccountRow instance. */
    constructor($$source: Partial<AccountRow> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("streams" in $$source)) {
            this["streams"] = 0;
        }
        if (!("consumers" in $$source)) {
            this["consumers"] = 0;
        }
        if (!("memory_bytes" in $$source)) {
            this["memory_bytes"] = 0;
        }
        if (!("store_bytes" in $$source)) {
            this["store_bytes"] = 0;
        }
        if (!("reserved_memory_bytes" in $$source)) {
            this["reserved_memory_bytes"] = 0;
        }
        if (!("reserved_store_bytes" in $$source)) {
            this["reserved_store_bytes"] = 0;
        }
        if (!("stream_names" in $$source)) {
            this["stream_names"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountRow instance from a string or object.
     */
    static createFrom($$source: any = {}): AccountRow {
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stream_names" in $$parsedSource) {
            $$parsedSource["stream_names"] = $$createField8_0($$parsedSource["stream_names"]);
        }
        return new AccountRow($$parsedSource as Partial<AccountRow>);
    }
}

/**
 * CallResult 与 jsadmin 同构（M4 裁定：包内私有重声明，零 churn）。
 */
export class CallResult {
    "error_code": string;
    "error": string;

    /** Creates a new CallResult instance. */
    constructor($$source: Partial<CallResult> = {}) {
        if (!("error_code" in $$source)) {
            this["error_code"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CallResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CallResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CallResult($$parsedSource as Partial<CallResult>);
    }
}

/**
 * ClusterOpResult：危险操作统一结果。
 */
export class ClusterOpResult {
    "error_code": string;
    "error": string;
    "old_leader": string;
    "new_leader": string;
    "streams_balanced": number;

    /**
     * 如 "new leader not observed within 5s"
     */
    "note": string;
    "elapsed_ms": number;

    /** Creates a new ClusterOpResult instance. */
    constructor($$source: Partial<ClusterOpResult> = {}) {
        if (!("error_code" in $$source)) {
            this["error_code"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("old_leader" in $$source)) {
            this["old_leader"] = "";
        }
        if (!("new_leader" in $$source)) {
            this["new_leader"] = "";
        }
        if (!("streams_balanced" in $$source)) {
            this["streams_balanced"] = 0;
        }
        if (!("note" in $$source)) {
            this["note"] = "";
        }
        if (!("elapsed_ms" in $$source)) {
            this["elapsed_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterOpResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterOpResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClusterOpResult($$parsedSource as Partial<ClusterOpResult>);
    }
}

export class ConnPageResult {
    "error_code": string;
    "error": string;
    "rows": ConnRow[];
    "offset": number;
    "limit": number;
    "total": number;

    /** Creates a new ConnPageResult instance. */
    constructor($$source: Partial<ConnPageResult> = {}) {
        if (!("error_code" in $$source)) {
            this["error_code"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnPageResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnPageResult {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField2_0($$parsedSource["rows"]);
        }
        return new ConnPageResult($$parsedSource as Partial<ConnPageResult>);
    }
}

/**
 * ConnRow / ConnPageResult：top 式连接明细（ConnInfo 裁剪——JWT/证书字段
 * 不上 wire，Global 9 的 wire 半边）。
 */
export class ConnRow {
    "cid": number;
    "kind": string;
    "ip": string;
    "port": number;
    "account": string;
    "user": string;
    "name": string;
    "lang": string;
    "version": string;
    "start_ms": number;
    "uptime": string;
    "idle": string;
    "rtt": string;
    "in_msgs": number;
    "out_msgs": number;
    "in_bytes": number;
    "out_bytes": number;
    "num_subs": number;
    "pending": number;

    /** Creates a new ConnRow instance. */
    constructor($$source: Partial<ConnRow> = {}) {
        if (!("cid" in $$source)) {
            this["cid"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("account" in $$source)) {
            this["account"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("lang" in $$source)) {
            this["lang"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("start_ms" in $$source)) {
            this["start_ms"] = 0;
        }
        if (!("uptime" in $$source)) {
            this["uptime"] = "";
        }
        if (!("idle" in $$source)) {
            this["idle"] = "";
        }
        if (!("rtt" in $$source)) {
            this["rtt"] = "";
        }
        if (!("in_msgs" in $$source)) {
            this["in_msgs"] = 0;
        }
        if (!("out_msgs" in $$source)) {
            this["out_msgs"] = 0;
        }
        if (!("in_bytes" in $$source)) {
            this["in_bytes"] = 0;
        }
        if (!("out_bytes" in $$source)) {
            this["out_bytes"] = 0;
        }
        if (!("num_subs" in $$source)) {
            this["num_subs"] = 0;
        }
        if (!("pending" in $$source)) {
            this["pending"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnRow instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnRow($$parsedSource as Partial<ConnRow>);
    }
}

/**
 * CreateSysWatchResult：单结构体返回（Global 19）。
 */
export class CreateSysWatchResult {
    "error_code": string;
    "error": string;
    "watch_id": string;

    /** Creates a new CreateSysWatchResult instance. */
    constructor($$source: Partial<CreateSysWatchResult> = {}) {
        if (!("error_code" in $$source)) {
            this["error_code"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("watch_id" in $$source)) {
            this["watch_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateSysWatchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateSysWatchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateSysWatchResult($$parsedSource as Partial<CreateSysWatchResult>);
    }
}

/**
 * MonitorServerRow 是服务器表一行（statsz + jsz 合并；Global 12 角色映射）。
 */
export class MonitorServerRow {
    "name": string;
    "id": string;
    "host": string;
    "cluster": string;
    "domain": string;
    "version": string;
    "online": boolean;
    "offline_since_ms": number;
    "uptime_seconds": number;
    "cpu": number;
    "mem_bytes": number;
    "cores": number;
    "connections": number;
    "total_connections": number;
    "routes": number;
    "gateways": number;
    "active_accounts": number;
    "slow_consumers": number;
    "js_enabled": boolean;

    /**
     * ""|disabled|meta_leader|voter
     */
    "js_role": string;
    "js_streams": number;
    "js_streams_leader": number;
    "js_consumers": number;
    "js_memory_bytes": number;
    "js_store_bytes": number;
    "js_max_memory_bytes": number;
    "js_max_store_bytes": number;

    /**
     * 离线行显示的最近失败原因
     */
    "error": string;

    /** Creates a new MonitorServerRow instance. */
    constructor($$source: Partial<MonitorServerRow> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("domain" in $$source)) {
            this["domain"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("online" in $$source)) {
            this["online"] = false;
        }
        if (!("offline_since_ms" in $$source)) {
            this["offline_since_ms"] = 0;
        }
        if (!("uptime_seconds" in $$source)) {
            this["uptime_seconds"] = 0;
        }
        if (!("cpu" in $$source)) {
            this["cpu"] = 0;
        }
        if (!("mem_bytes" in $$source)) {
            this["mem_bytes"] = 0;
        }
        if (!("cores" in $$source)) {
            this["cores"] = 0;
        }
        if (!("connections" in $$source)) {
            this["connections"] = 0;
        }
        if (!("total_connections" in $$source)) {
            this["total_connections"] = 0;
        }
        if (!("routes" in $$source)) {
            this["routes"] = 0;
        }
        if (!("gateways" in $$source)) {
            this["gateways"] = 0;
        }
        if (!("active_accounts" in $$source)) {
            this["active_accounts"] = 0;
        }
        if (!("slow_consumers" in $$source)) {
            this["slow_consumers"] = 0;
        }
        if (!("js_enabled" in $$source)) {
            this["js_enabled"] = false;
        }
        if (!("js_role" in $$source)) {
            this["js_role"] = "";
        }
        if (!("js_streams" in $$source)) {
            this["js_streams"] = 0;
        }
        if (!("js_streams_leader" in $$source)) {
            this["js_streams_leader"] = 0;
        }
        if (!("js_consumers" in $$source)) {
            this["js_consumers"] = 0;
        }
        if (!("js_memory_bytes" in $$source)) {
            this["js_memory_bytes"] = 0;
        }
        if (!("js_store_bytes" in $$source)) {
            this["js_store_bytes"] = 0;
        }
        if (!("js_max_memory_bytes" in $$source)) {
            this["js_max_memory_bytes"] = 0;
        }
        if (!("js_max_store_bytes" in $$source)) {
            this["js_max_store_bytes"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorServerRow instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorServerRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitorServerRow($$parsedSource as Partial<MonitorServerRow>);
    }
}

/**
 * MonitorSnapshot 是 monitor:snapshot 事件与 GetMonitoringSnapshot 的载荷。
 */
export class MonitorSnapshot {
    "servers": MonitorServerRow[];
    "sys_available": boolean;
    "sys_reason": string;
    "polled_at_ms": number;
    "cycle_ms": number;
    "rtt_ms": number;
    "poll_interval_seconds": number;

    /** Creates a new MonitorSnapshot instance. */
    constructor($$source: Partial<MonitorSnapshot> = {}) {
        if (!("servers" in $$source)) {
            this["servers"] = [];
        }
        if (!("sys_available" in $$source)) {
            this["sys_available"] = false;
        }
        if (!("sys_reason" in $$source)) {
            this["sys_reason"] = "";
        }
        if (!("polled_at_ms" in $$source)) {
            this["polled_at_ms"] = 0;
        }
        if (!("cycle_ms" in $$source)) {
            this["cycle_ms"] = 0;
        }
        if (!("rtt_ms" in $$source)) {
            this["rtt_ms"] = 0;
        }
        if (!("poll_interval_seconds" in $$source)) {
            this["poll_interval_seconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorSnapshot {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("servers" in $$parsedSource) {
            $$parsedSource["servers"] = $$createField0_0($$parsedSource["servers"]);
        }
        return new MonitorSnapshot($$parsedSource as Partial<MonitorSnapshot>);
    }
}

/**
 * ServerDetailResult / GetServerDetail：varz + healthz 定向报表。
 */
export class ServerDetail {
    "row": MonitorServerRow;
    "start_ms": number;
    "leaf_nodes": number;
    "num_subs": number;
    "sent_msgs": number;
    "sent_bytes": number;
    "recv_msgs": number;
    "recv_bytes": number;

    /**
     * ""=未知/无权限
     */
    "health_status": string;
    "health_error": string;
    "health_detail": string;

    /** Creates a new ServerDetail instance. */
    constructor($$source: Partial<ServerDetail> = {}) {
        if (!("row" in $$source)) {
            this["row"] = (new MonitorServerRow());
        }
        if (!("start_ms" in $$source)) {
            this["start_ms"] = 0;
        }
        if (!("leaf_nodes" in $$source)) {
            this["leaf_nodes"] = 0;
        }
        if (!("num_subs" in $$source)) {
            this["num_subs"] = 0;
        }
        if (!("sent_msgs" in $$source)) {
            this["sent_msgs"] = 0;
        }
        if (!("sent_bytes" in $$source)) {
            this["sent_bytes"] = 0;
        }
        if (!("recv_msgs" in $$source)) {
            this["recv_msgs"] = 0;
        }
        if (!("recv_bytes" in $$source)) {
            this["recv_bytes"] = 0;
        }
        if (!("health_status" in $$source)) {
            this["health_status"] = "";
        }
        if (!("health_error" in $$source)) {
            this["health_error"] = "";
        }
        if (!("health_detail" in $$source)) {
            this["health_detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerDetail {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("row" in $$parsedSource) {
            $$parsedSource["row"] = $$createField0_0($$parsedSource["row"]);
        }
        return new ServerDetail($$parsedSource as Partial<ServerDetail>);
    }
}

export class ServerDetailResult {
    "error_code": string;
    "error": string;
    "detail": ServerDetail | null;

    /** Creates a new ServerDetailResult instance. */
    constructor($$source: Partial<ServerDetailResult> = {}) {
        if (!("error_code" in $$source)) {
            this["error_code"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerDetailResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerDetailResult {
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("detail" in $$parsedSource) {
            $$parsedSource["detail"] = $$createField2_0($$parsedSource["detail"]);
        }
        return new ServerDetailResult($$parsedSource as Partial<ServerDetailResult>);
    }
}

/**
 * SysWatchSpec 是 CreateSysWatch 的入参：闭集类型过滤（Global 10）+ 可选的
 * subject 正则（过滤发生在入队之前，filtered_total 单独计数）。
 */
export class SysWatchSpec {
    "types": string[];
    "regex": string;

    /** Creates a new SysWatchSpec instance. */
    constructor($$source: Partial<SysWatchSpec> = {}) {
        if (!("types" in $$source)) {
            this["types"] = [];
        }
        if (!("regex" in $$source)) {
            this["regex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SysWatchSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): SysWatchSpec {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("types" in $$parsedSource) {
            $$parsedSource["types"] = $$createField0_0($$parsedSource["types"]);
        }
        return new SysWatchSpec($$parsedSource as Partial<SysWatchSpec>);
    }
}

// Private type creation functions
const $$createType0 = AccountRow.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = ConnRow.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = MonitorServerRow.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ServerDetail.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
