// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AccountListResult {
    "error_code": string;
    "error": string;
    "accounts": AccountRow[] | null;
}

/**
 * AccountRow：账户信息与统计（serverdata.CollectAccounts 聚合结果）。
 */
export interface AccountRow {
    "name": string;
    "id": string;
    "streams": number;
    "consumers": number;
    "memory_bytes": number;
    "store_bytes": number;
    "reserved_memory_bytes": number;
    "reserved_store_bytes": number;
    "stream_names": string[] | null;
}

/**
 * CallResult 与 jsadmin 同构（M4 裁定：包内私有重声明，零 churn）。
 */
export interface CallResult {
    "error_code": string;
    "error": string;
}

/**
 * ClusterOpResult：危险操作统一结果。
 */
export interface ClusterOpResult {
    "error_code": string;
    "error": string;
    "old_leader": string;
    "new_leader": string;
    "streams_balanced": number;

    /**
     * 如 "new leader not observed within 5s"
     */
    "note": string;
    "elapsed_ms": number;
}

export interface ConnPageResult {
    "error_code": string;
    "error": string;
    "rows": ConnRow[] | null;
    "offset": number;
    "limit": number;
    "total": number;
}

/**
 * ConnRow / ConnPageResult：top 式连接明细（ConnInfo 裁剪——JWT/证书字段
 * 不上 wire，Global 9 的 wire 半边）。
 */
export interface ConnRow {
    "cid": number;
    "kind": string;
    "ip": string;
    "port": number;
    "account": string;
    "user": string;
    "name": string;
    "lang": string;
    "version": string;
    "start_ms": number;
    "uptime": string;
    "idle": string;
    "rtt": string;
    "in_msgs": number;
    "out_msgs": number;
    "in_bytes": number;
    "out_bytes": number;
    "num_subs": number;
    "pending": number;
}

/**
 * CreateSysWatchResult：单结构体返回（Global 19）。
 */
export interface CreateSysWatchResult {
    "error_code": string;
    "error": string;
    "watch_id": string;
}

/**
 * MonitorServerRow 是服务器表一行（statsz + jsz 合并；Global 12 角色映射）。
 */
export interface MonitorServerRow {
    "name": string;
    "id": string;
    "host": string;
    "cluster": string;
    "domain": string;
    "version": string;
    "online": boolean;
    "offline_since_ms": number;
    "uptime_seconds": number;
    "cpu": number;
    "mem_bytes": number;
    "cores": number;
    "connections": number;
    "total_connections": number;
    "routes": number;
    "gateways": number;
    "active_accounts": number;
    "slow_consumers": number;
    "js_enabled": boolean;

    /**
     * ""|disabled|meta_leader|voter
     */
    "js_role": string;
    "js_streams": number;
    "js_streams_leader": number;
    "js_consumers": number;
    "js_memory_bytes": number;
    "js_store_bytes": number;
    "js_max_memory_bytes": number;
    "js_max_store_bytes": number;

    /**
     * 离线行显示的最近失败原因
     */
    "error": string;
}

/**
 * MonitorSnapshot 是 monitor:snapshot 事件与 GetMonitoringSnapshot 的载荷。
 */
export interface MonitorSnapshot {
    "servers": MonitorServerRow[] | null;
    "sys_available": boolean;
    "sys_reason": string;
    "polled_at_ms": number;
    "cycle_ms": number;
    "rtt_ms": number;
    "poll_interval_seconds": number;
}

/**
 * ServerDetailResult / GetServerDetail：varz + healthz 定向报表。
 */
export interface ServerDetail {
    "row": MonitorServerRow;
    "start_ms": number;
    "leaf_nodes": number;
    "num_subs": number;
    "sent_msgs": number;
    "sent_bytes": number;
    "recv_msgs": number;
    "recv_bytes": number;

    /**
     * ""=未知/无权限
     */
    "health_status": string;
    "health_error": string;
    "health_detail": string;
}

export interface ServerDetailResult {
    "error_code": string;
    "error": string;
    "detail": ServerDetail | null;
}

/**
 * SysWatchSpec 是 CreateSysWatch 的入参：闭集类型过滤（Global 10）+ 可选的
 * subject 正则（过滤发生在入队之前，filtered_total 单独计数）。
 */
export interface SysWatchSpec {
    "types": string[] | null;
    "regex": string;
}
