// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as connections$0 from "../connections/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateSysWatch 订阅 $SYS 事件流：校验（闭集类型/正则）→ subjects =
 * EventSubjects(types, JSEventPrefix, domain) → 逐 subject Subscribe（长生命
 * 周期 cancel ctx）→ 回调 ingest（regex 过滤 → 解析 → 有界队列）→ 单发射
 * goroutine emit("sys:event")。部分订阅失败时回滚已建订阅（fail closed）。
 */
export function CreateSysWatch(spec: $models.SysWatchSpec): $CancellablePromise<$models.CreateSysWatchResult> {
    return $Call.ByID(2330680478, spec);
}

/**
 * GetMonitoringSnapshot 返回最近一轮缓存快照；未启动过时是零值
 * （SysAvailable=false）。
 */
export function GetMonitoringSnapshot(): $CancellablePromise<$models.MonitorSnapshot> {
    return $Call.ByID(1913593440);
}

/**
 * GetServerDetail 节点报表：定向 VARZ + HEALTHZ。varz 失败 → server 原文
 * （部分主题无权限时该面板显示原文，其余面板不受影响，Global 3 的失败面）；
 * healthz 失败容忍 → HealthStatus="" + HealthError 原文。
 */
export function GetServerDetail(name: string): $CancellablePromise<$models.ServerDetailResult> {
    return $Call.ByID(4201275236, name);
}

/**
 * KickConnection 断开指定连接：resolveServerID → 定向 KICK。拒绝/失败原文
 * 透传（Global 4）。日志只记服务器名与 cid，不记用户身份（§13.3）。
 */
export function KickConnection(name: string, cid: number): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(3888311400, name, cid);
}

/**
 * ListAccounts 账户信息与统计：jsz 聚合 → AccountRow（按 Name 排序）。
 * 失败降级面（§8.3.1）：无 JS/无 $SYS 权限等 CollectAccounts 失败 → Ok 结果
 * + 空列表 + Error 原文（面板级降级，不 error_code 化）；连接缺失才走标准
 * not_connected 路径。只记账户/stream 聚合计数（§13.3）。
 */
export function ListAccounts(): $CancellablePromise<$models.AccountListResult> {
    return $Call.ByID(3201350538);
}

/**
 * ListServerConnections 连接明细：ValidateConnQuery 先行 → resolveServerID →
 * 定向 CONNZ（Username:true 才有 user 字段；Sort/Offset/Limit 服务端分页）。
 * Total 取 data.Total；行映射显式字段白名单（JWT/TLS 证书/Tags 不上 wire，
 * Global 9 的 wire 半边）。
 */
export function ListServerConnections(name: string, sort: string, offset: number, limit: number): $CancellablePromise<$models.ConnPageResult> {
    return $Call.ByID(1750766526, name, sort, offset, limit);
}

/**
 * MetaPeerRemove 从元集群移除 peer：resolveMetaLeader 的 jsz 里解析副本——
 * r.Name == peer || r.Peer == peer（natscli 同款）；id 已知时按 id 移除
 * （服务端 id 寻址最精确），否则按名。找不到 → not_found。
 */
export function MetaPeerRemove(peer: string): $CancellablePromise<$models.ClusterOpResult> {
    return $Call.ByID(441981975, peer);
}

/**
 * MetaStepDown 元集群 leader step-down：域守卫 → resolveMetaLeader → 显式
 * 无域 manager（natscli parity）→ MetaLeaderStandDown(nil) → 轮询新 leader。
 */
export function MetaStepDown(): $CancellablePromise<$models.ClusterOpResult> {
    return $Call.ByID(364005833);
}

/**
 * NotifyConnState：非 connected 一律停轮询并停全部 sys watch（事件 watch
 * 断连全停，与 M4 buckets watcher 对齐）。
 */
export function NotifyConnState(ev: connections$0.StateEvent): $CancellablePromise<void> {
    return $Call.ByID(1095425926, ev);
}

export function StartMonitoring(): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(3169526816);
}

/**
 * StopMonitoring 幂等；等 poll goroutine 退出后再返回，避免与下一次
 * Start 竞争 emit 顺序。
 */
export function StopMonitoring(): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(3551371480);
}

/**
 * StopSysWatch 关停单个 sys watch：close done + stops（cancel + Unsubscribe）+
 * 注册表删除。未知 id → not_found。
 */
export function StopSysWatch(watchId: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(684757450, watchId);
}

/**
 * StreamBalance 用 jsm.go/balancer 平衡流 leader 分布。logger 用官方
 * api.NewDiscardLogger()——api.Logger 是五方法接口（Tracef/Debugf/Infof/
 * Warnf/Errorf），不手写适配器；balancer 内部细节不外泄，结果只记数量。
 */
export function StreamBalance(stream: string): $CancellablePromise<$models.ClusterOpResult> {
    return $Call.ByID(3591297434, stream);
}

/**
 * StreamPeerRemove 从流 RAFT 组移除副本（LoadStream → RemoveRAFTPeer）。
 * 单飞 target 取流名：同一流的副本移除串行（RAFT 组收敛期间叠加移除有风险）。
 */
export function StreamPeerRemove(stream: string, peer: string): $CancellablePromise<$models.ClusterOpResult> {
    return $Call.ByID(310836130, stream, peer);
}

/**
 * StreamStepDown 流 leader step-down：域感知句柄 → LoadStream → 未集群拒绝
 * → LeaderStepDown() → 轮询新 leader。
 */
export function StreamStepDown(stream: string): $CancellablePromise<$models.ClusterOpResult> {
    return $Call.ByID(436450800, stream);
}
