// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateInfo describes the outcome of an update check.
 */
export interface UpdateInfo {
    "current": string;
    "latest": string;
    "url": string;
    "has_update": boolean;
}
