// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade exposing app metadata and an on-demand
 * update check to the frontend (registered alongside the settings, logging
 * and connections services).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppVersion returns the running application version ("0.1.0" during M1).
 */
export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(1061545313);
}

/**
 * CheckUpdate queries GitHub for the latest release of this project with a
 * 5s timeout. The startup auto-check emits "update:available" instead; this
 * method backs any future manual "check for updates" affordance.
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(3567056885);
}
