// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MessagingService fronts the messaging package for the Wails service
 * registry. Construct with NewMessagingService; all methods are safe for
 * concurrent use (the underlying Publish/Request/Trace functions and the
 * SessionManager are).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearSession resets the ring buffer and display counters; the subscription
 * keeps receiving. Fails on unknown or closed sessions.
 */
export function ClearSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(2176779541, id);
}

/**
 * CloseSession unsubscribes and marks the session closed. Idempotent.
 */
export function CloseSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(3196261074, id);
}

/**
 * CreateSession subscribes spec.Subject and starts the session. Blank fields
 * resolve per call from settings: BufferSize <= 0 from session_buffer_size,
 * a non-realtime/batch PushMode from session_push_batching (batch when true,
 * realtime otherwise). Refused with an ErrNotConnected error while the
 * manager is disconnected (fail-closed: see the package comment).
 */
export function CreateSession(spec: $models.SessionSpec): $CancellablePromise<$models.SessionState> {
    return $Call.ByID(1076719914, spec);
}

/**
 * DataChannel reports the hub endpoint; zero value when the hub is absent
 * (frontend then falls back to wails events — which also carry no data in
 * that mode because the emit path is active, so the pairing stays coherent).
 */
export function DataChannel(): $CancellablePromise<$models.DataChannelInfo> {
    return $Call.ByID(1089283573);
}

/**
 * ListSessions returns a snapshot of every session (including closed ones),
 * sorted by ID. Never nil so the frontend can map over it.
 */
export function ListSessions(): $CancellablePromise<$models.SessionState[] | null> {
    return $Call.ByID(1271180083);
}

/**
 * PauseSession freezes the session display; the subscription keeps receiving.
 * Idempotent; fails on unknown or closed sessions.
 */
export function PauseSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(971977184, id);
}

/**
 * Publish sends one message (core NATS or, with JetStream, an acked publish).
 * A blank TimeoutMs resolves from the settings request_timeout_seconds. A
 * disconnected manager yields the failed ErrNotConnected result, not an
 * error.
 */
export function Publish(form: $models.PubForm): $CancellablePromise<$models.PubResult> {
    return $Call.ByID(3011724409, form);
}

/**
 * Request sends one request and waits for a single reply, with the same
 * blank-timeout and disconnect semantics as Publish.
 */
export function Request(form: $models.ReqForm): $CancellablePromise<$models.ReqResult> {
    return $Call.ByID(633040719, form);
}

/**
 * ResumeSession unfreezes the session; paused-period messages are never
 * replayed. Idempotent; fails on unknown or closed sessions.
 */
export function ResumeSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(1294293407, id);
}

/**
 * Trace sends one probe through the server message-tracing API (NATS Server
 * 2.11+) and returns the unfolded hop tree. It shares the Publish/Request
 * timeout and disconnect semantics; ErrTraceOldServer reports a too-old
 * server.
 */
export function Trace(form: $models.TraceForm): $CancellablePromise<$models.TraceHop> {
    return $Call.ByID(95514463, form);
}
