// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JSPosition positions a session within a JetStream stream (spec §6.4).
 * Mode is a closed set: all | new | start_sequence | start_time. StartSeq is
 * the stream sequence for start_sequence; StartTime an RFC3339 timestamp for
 * start_time.
 */
export interface JSPosition {
    "mode": string;
    "start_seq"?: number;
    "start_time"?: string;
}

/**
 * PubForm is one publish request. JetStream selects the acked publish path;
 * TimeoutMs (<=0 -> 5000) is the ack wait for that path only.
 */
export interface PubForm {
    "Subject": string;
    "Headers": { [_ in string]?: string[] | null } | null;
    "Payload": string | null;
    "JetStream": boolean;
    "TimeoutMs": number;
}

/**
 * PubResult reports one publish. JSON tags are lowercase snake per the frozen
 * frontend contract. Stream/Sequence/Duplicate are only meaningful when
 * JetStream is true.
 */
export interface PubResult {
    "ok": boolean;
    "jetstream": boolean;
    "stream"?: string;
    "sequence"?: number;
    "duplicate"?: boolean;
    "elapsed_ms": number;
    "error"?: string;
}

/**
 * PushMode selects how messages in a subscription session are pushed to
 * the frontend (spec §6.4): realtime pushes one single-element batch per
 * arriving message, batch coalesces up to 500 messages or 100ms
 * (whichever comes first) into one batch.
 */
export enum PushMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The two push modes (spec §6.4); realtime is the default.
     */
    PushRealtime = "realtime",
    PushBatch = "batch",
};

/**
 * ReqForm is one request (reply expected on an auto-generated inbox).
 */
export interface ReqForm {
    "Subject": string;
    "Headers": { [_ in string]?: string[] | null } | null;
    "Payload": string | null;
    "TimeoutMs": number;
}

/**
 * ReqResult reports one request. NoResponder mirrors nats.ErrNoResponders;
 * Payload carries the response body (never logged anywhere).
 */
export interface ReqResult {
    "ok": boolean;
    "payload"?: string | null;
    "headers"?: { [_ in string]?: string[] | null } | null;
    "elapsed_ms": number;
    "no_responder": boolean;
    "error"?: string;
}

/**
 * SessionSpec is the creation request for one subscription session
 * (spec §6.4). BufferSize <= 0 means "use the configured default" and is
 * resolved before the messaging layer sees the value; JSPosition selects
 * JetStream replay positioning (nil / mode "new" = plain core subscription).
 * The JSON tags are a frozen frontend contract.
 */
export interface SessionSpec {
    "subject": string;
    "push_mode": PushMode;
    "buffer_size": number;
    "js_position"?: JSPosition | null;
}

/**
 * SessionState is the status snapshot of one subscription session, as pushed
 * via EventSessionState (throttled to 250ms) and returned by List(). The JSON
 * tags are a frozen frontend contract. State is a closed set:
 * running | paused | closed. Error carries the verbatim server error text for
 * sessions the server refused (spec §6.4) and is otherwise empty.
 */
export interface SessionState {
    "id": string;
    "subject": string;
    "state": string;
    "push_mode": PushMode;
    "rate_msg_s": number;
    "total": number;
    "dropped": number;
    "buffer_used": number;
    "error"?: string;
}

/**
 * TraceForm is one trace request. Deliver=false (the default) traces the route
 * only: the message carries Nats-Trace-Only and never reaches the final
 * subject. TimeoutMs (<=0 -> 5000) bounds each trace-response wait.
 */
export interface TraceForm {
    "Subject": string;
    "Headers": { [_ in string]?: string[] | null } | null;
    "Payload": string | null;
    "Deliver": boolean;
    "TimeoutMs": number;
}

/**
 * TraceHop is one node of the trace tree. Kind is a closed set: "ingress",
 * "egress", "mapping", "service_import", "stream_export", "jetstream",
 * "no_interest". Detail carries the natscli-style human description; Children
 * nests remote-server hops (egress -> next server's ingress).
 */
export interface TraceHop {
    "kind": string;
    "detail": string;
    "children"?: TraceHop[] | null;
}
