// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DataChannelInfo is the loopback WS endpoint the frontend uses for the
 * session data plane (§7.1.3 batches). Token is a per-boot capability
 * credential: it must never be logged (§13.3).
 */
export interface DataChannelInfo {
    "url": string;
    "token": string;
}

/**
 * JSPosition positions a session within a JetStream stream (spec §6.4).
 * Mode is a closed set: all | new | start_sequence | start_time. StartSeq is
 * the stream sequence for start_sequence; StartTime an RFC3339 timestamp for
 * start_time.
 */
export interface JSPosition {
    "mode": string;
    "start_seq"?: number;
    "start_time"?: string;
}

/**
 * PubForm is one publish request. JetStream selects the acked publish path;
 * TimeoutMs (<=0 -> settings default / 5000) is the ack wait for that path
 * only. The JSON tags are the frozen Wails-binding contract (lowercase snake,
 * like every other messaging wire type).
 */
export interface PubForm {
    "subject": string;
    "headers": { [_ in string]?: string[] | null } | null;

    /**
     * Go json encodes []byte as base64
     */
    "payload": string | null;
    "jetstream": boolean;
    "timeout_ms": number;
}

/**
 * PubResult reports one publish. JSON tags are lowercase snake per the frozen
 * frontend contract. Stream/Sequence/Duplicate are only meaningful when
 * JetStream is true.
 */
export interface PubResult {
    "ok": boolean;
    "jetstream": boolean;
    "stream"?: string;
    "sequence"?: number;
    "duplicate"?: boolean;
    "elapsed_ms": number;
    "error"?: string;
}

/**
 * PushMode selects how messages in a subscription session are pushed to
 * the frontend (spec §6.4): realtime pushes one single-element batch per
 * arriving message, batch coalesces up to 500 messages or 100ms
 * (whichever comes first) into one batch.
 */
export enum PushMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The two push modes (spec §6.4); realtime is the default.
     */
    PushRealtime = "realtime",
    PushBatch = "batch",
};

/**
 * ReqForm is one request (reply expected on an auto-generated inbox). The
 * JSON tags are the frozen Wails-binding contract (lowercase snake).
 */
export interface ReqForm {
    "subject": string;
    "headers": { [_ in string]?: string[] | null } | null;

    /**
     * Go json encodes []byte as base64
     */
    "payload": string | null;
    "timeout_ms": number;
}

/**
 * ReqResult reports one request. NoResponder mirrors nats.ErrNoResponders;
 * Payload carries the response body (never logged anywhere).
 */
export interface ReqResult {
    "ok": boolean;
    "payload"?: string | null;
    "headers"?: { [_ in string]?: string[] | null } | null;
    "elapsed_ms": number;
    "no_responder": boolean;
    "error"?: string;
}

/**
 * SessionSpec is the creation request for one subscription session
 * (spec §6.4). BufferSize <= 0 means "use the configured default" and is
 * resolved before the messaging layer sees the value; JSPosition selects
 * JetStream replay positioning (nil = plain core subscription; every
 * non-nil JSPosition — including mode "new" — takes the JetStream path,
 * and an empty mode is rejected). HeaderFilters optionally restricts
 * receipts to messages whose headers carry every listed key with an exactly
 * equal value (AND semantics, case-sensitive keys; matching happens Go-side
 * BEFORE any counting/ring/push so flood-rate streams are filtered near the
 * source). nil / empty means "no filtering". The service layer bounds the
 * form to <= 8 pairs with keys/values <= 256 bytes.
 * The JSON tags are a frozen frontend contract.
 */
export interface SessionSpec {
    "subject": string;
    "push_mode": PushMode;
    "buffer_size": number;
    "js_position"?: JSPosition | null;
    "header_filters"?: { [_ in string]?: string } | null;
}

/**
 * SessionState is the status snapshot of one subscription session, as pushed
 * via EventSessionState (throttled to 250ms) and returned by List(). The JSON
 * tags are a frozen frontend contract. State is a closed set:
 * running | paused | closed. Error carries the verbatim server error text for
 * sessions the server refused (spec §6.4) and is otherwise empty.
 * 
 * Conservation semantics (extended for header filtering in M3): a session's
 * received messages decompose exactly as
 * 
 * 	received == Total + Filtered
 * 
 * where Filtered counts receipts dropped by the session's HeaderFilters
 * before any further processing. The delivered side keeps the M2 invariants
 * unchanged: Total == emitted and Total == Dropped + BufferUsed (both
 * computed over the delivered messages only — filtered receipts never touch
 * the ring, the pusher, or the rate meter).
 */
export interface SessionState {
    "id": string;
    "subject": string;
    "state": string;
    "push_mode": PushMode;
    "rate_msg_s": number;
    "total": number;
    "filtered": number;
    "dropped": number;
    "buffer_used": number;
    "error"?: string;
}

/**
 * TraceForm is one trace request. Deliver=false (the default) traces the route
 * only: the message carries Nats-Trace-Only and never reaches the final
 * subject. TimeoutMs (<=0 -> settings default / 5000) bounds each
 * trace-response wait. The JSON tags are the frozen Wails-binding contract
 * (lowercase snake).
 */
export interface TraceForm {
    "subject": string;
    "headers": { [_ in string]?: string[] | null } | null;

    /**
     * Go json encodes []byte as base64
     */
    "payload": string | null;
    "deliver": boolean;
    "timeout_ms": number;
}

/**
 * TraceHop is one node of the trace tree. Kind is a closed set: "ingress",
 * "egress", "mapping", "service_import", "stream_export", "jetstream",
 * "no_interest". Detail carries the natscli-style human description; Children
 * nests remote-server hops (egress -> next server's ingress).
 */
export interface TraceHop {
    "kind": string;
    "detail": string;
    "children"?: TraceHop[] | null;
}
