// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ContextForm is the write model used to create or edit a context.
 * Empty string fields are skipped when saving, so an edit keeps the
 * previously stored value for any field the form leaves empty.
 */
export interface ContextForm {
    "name": string;
    "description": string;
    "url": string;
    "user": string;
    "password": string;
    "token": string;
    "creds": string;
    "nkey": string;
    "cert": string;
    "key": string;
    "ca": string;
    "js_domain": string;
    "js_api_prefix": string;
    "js_event_prefix": string;
    "inbox_prefix": string;
    "socks_proxy": string;
    "color_scheme": string;
    "tls_first": boolean;
}

/**
 * ContextSummary is the read model for a stored context, as shown in
 * connection lists and switchers.
 */
export interface ContextSummary {
    "name": string;
    "description": string;
    "url": string;

    /**
     * creds | nkey | token | userpass | none
     */
    "auth_type": string;
    "color_scheme": string;
}

/**
 * State is a connection lifecycle state of the Manager (spec §7.3).
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The five connection states (spec §7.3); values are the wire/UI names.
     */
    StateDisconnected = "disconnected",
    StateConnecting = "connecting",
    StateConnected = "connected",
    StateReconnecting = "reconnecting",
    StateFailed = "failed",
};

/**
 * StateEvent is the payload of EventConnState: the full state of the
 * active connection at the moment of the transition. Since is the RFC3339
 * timestamp of when the current state was entered, RttMs the last
 * round-trip time measured while connected (0 otherwise), and Reason the
 * error text for failed states.
 */
export interface StateEvent {
    "context": string;
    "state": State;
    "since": string;
    "rtt_ms": number;
    "reason"?: string;
}

/**
 * TestResult is the outcome of Manager.CheckConnection: whether the
 * probe connection could be established, its averaged RTT, and whether a
 * JetStream account was reachable on the other end.
 */
export interface TestResult {
    "ok": boolean;
    "rtt_ms": number;
    "jetstream": boolean;
    "error"?: string;
}
