// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade over the context Store (CRUD) and the
 * connection Manager (lifecycle), exposing the exact method set the
 * frontend bindings need (Task 10). Bound methods take no request context
 * (nothing here is cancellable from the UI) and use context.Background()
 * internally.
 * 
 * persistActive is invoked after every successful Connect so main.go can
 * record settings.LastActiveContext (load-modify-save); a persist failure
 * is logged but does not fail the Connect.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckConnection dials a throwaway connection from form (nothing is
 * persisted, the live Manager state machine is untouched) and reports
 * RTT and JetStream availability.
 */
export function CheckConnection(form: $models.ContextForm): $CancellablePromise<$models.TestResult> {
    return $Call.ByID(2187232881, form);
}

/**
 * ConnSnapshot returns the Manager's current state (frontend hydration on
 * mount, covering transitions that fired before the UI subscribed).
 */
export function ConnSnapshot(): $CancellablePromise<$models.StateEvent> {
    return $Call.ByID(2923031445);
}

/**
 * Connect establishes the live connection for the stored context name,
 * replacing any active one; on success the name is persisted as the last
 * active context (spec §6.1).
 */
export function Connect(name: string): $CancellablePromise<void> {
    return $Call.ByID(2053282591, name);
}

/**
 * CopyContext duplicates the stored context src under name.
 */
export function CopyContext(src: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3410518845, src, name);
}

/**
 * DeleteContext removes the named context (unselecting it first when it
 * is the registry's selected context).
 */
export function DeleteContext(name: string): $CancellablePromise<void> {
    return $Call.ByID(1875069867, name);
}

/**
 * Disconnect user-closes the live connection. It cannot fail.
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(722712529);
}

/**
 * EnvWarnings lists the NATS_* override variables currently set.
 */
export function EnvWarnings(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1007420419);
}

/**
 * GetContextForm loads the full stored context as a form so the edit
 * dialog prefills every field (Task 6 caution: edits skip empty fields,
 * so the form must show stored values to keep "unchanged" the norm),
 * together with the context file's mtime at load time. The mtime is
 * snapshotted before the load so a file written concurrently is seen as
 * externally modified at save time rather than adopted silently.
 */
export function GetContextForm(name: string): $CancellablePromise<$models.ContextFormResult> {
    return $Call.ByID(2552732282, name);
}

/**
 * ListContexts returns every stored context summary, ordered by name. On
 * error an empty (non-nil) slice is returned and the error logged — the
 * UI renders an empty list, not a crash.
 */
export function ListContexts(): $CancellablePromise<$models.ContextSummary[] | null> {
    return $Call.ByID(1890593355);
}

/**
 * SaveContext creates or edits the context described by form. A
 * knownModTimeMs > 0 (the GetContextForm snapshot) makes the save fail
 * with ErrContextModified when the file changed on disk in between;
 * 0 skips the check (creates and the frontend's "keep mine" path).
 */
export function SaveContext(form: $models.ContextForm, knownModTimeMs: number): $CancellablePromise<void> {
    return $Call.ByID(2616488113, form, knownModTimeMs);
}
