// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JetAdminService is the Wails-bound facade for stream/consumer
 * administration (spec §6.6/§6.7). Settings are read per call; every
 * method returns a CallResult-embedding struct, never a bare error, so
 * the frontend can branch on error_code (spec §8.5.2).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CopyStream(src: string, newName: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(2039655769, src, newName).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CreateStream(form: $models.StreamForm): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(3895247320, form).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DeleteStream(name: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(2288360423, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetStreamDetail(name: string): $CancellablePromise<$models.StreamDetail> {
    return $Call.ByID(3400850361, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListStreams(): $CancellablePromise<$models.ListStreamsResult> {
    return $Call.ByID(1500379901).then(($result: any) => {
        return $$createType2($result);
    });
}

export function PurgeStream(name: string, keep: number, upToSeq: number, subject: string): $CancellablePromise<$models.PurgeResult> {
    return $Call.ByID(321277507, name, keep, upToSeq, subject).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SealStream(name: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(475763909, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UpdateStream(form: $models.StreamForm): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(2714303341, form).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CallResult.createFrom;
const $$createType1 = $models.StreamDetail.createFrom;
const $$createType2 = $models.ListStreamsResult.createFrom;
const $$createType3 = $models.PurgeResult.createFrom;
