// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JetAdminService is the Wails-bound facade for stream/consumer
 * administration (spec §6.6/§6.7). Settings are read per call; every
 * method returns a CallResult-embedding struct, never a bare error, so
 * the frontend can branch on error_code (spec §8.5.2).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BackupStream(stream: string, dir: string, includeConsumers: boolean): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(3917122618, stream, dir, includeConsumers);
}

/**
 * BrowseStream returns one stateless page of a stream's messages. Page state
 * lives entirely in the request (StartSeq = first stream sequence to return,
 * inclusive; NextStartSeq = last returned seq + 1), so the frontend can deep
 * link / jump to any position without a server-side cursor. Pages are served
 * through a throwaway ephemeral pull consumer (DeliverByStartSequence +
 * AckNone) that is deleted on return; the count+1 fetch over-read only to
 * compute HasMore — the extra message is never returned (no ack needed, no
 * side effect).
 */
export function BrowseStream(req: $models.BrowserPageRequest): $CancellablePromise<$models.BrowserPageResult> {
    return $Call.ByID(273316478, req);
}

export function CopyConsumer(stream: string, name: string, newName: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(3974582973, stream, name, newName);
}

export function CopyStream(src: string, newName: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(2039655769, src, newName);
}

export function CreateConsumer(form: $models.ConsumerForm): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(2766214020, form);
}

export function CreateStream(form: $models.StreamForm): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(3895247320, form);
}

export function DeleteConsumer(stream: string, name: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(3636108607, stream, name);
}

export function DeleteStream(name: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(2288360423, name);
}

export function GetConsumerDetail(stream: string, name: string): $CancellablePromise<$models.ConsumerDetail> {
    return $Call.ByID(2433991061, stream, name);
}

export function GetStreamDetail(name: string): $CancellablePromise<$models.StreamDetail> {
    return $Call.ByID(3400850361, name);
}

/**
 * GetStreamMessage returns one message with its FULL payload (never
 * truncated — the 64KB preview cap is browse-row-only). Reads go through
 * jsm's direct stream message GET, so the path works on mirror/source
 * streams too and 404s on a deleted/never-existing sequence.
 */
export function GetStreamMessage(stream: string, seq: number): $CancellablePromise<$models.GetMsgResult> {
    return $Call.ByID(633748527, stream, seq);
}

export function ListConsumers(stream: string): $CancellablePromise<$models.ListConsumersResult> {
    return $Call.ByID(1975139201, stream);
}

export function ListStreams(filter: string): $CancellablePromise<$models.ListStreamsResult> {
    return $Call.ByID(1500379901, filter);
}

export function PauseConsumer(stream: string, name: string, seconds: number): $CancellablePromise<$models.PauseResult> {
    return $Call.ByID(1797297558, stream, name, seconds);
}

/**
 * PickBackupDirectory opens the native directory chooser. "" means the
 * user cancelled (no error surfaced to the UI).
 */
export function PickBackupDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3656915366);
}

export function PreviewNext(stream: string, name: string, batch: number, autoAck: boolean): $CancellablePromise<$models.PreviewNextResult> {
    return $Call.ByID(1928994473, stream, name, batch, autoAck);
}

export function PurgeStream(name: string, keep: number, upToSeq: number, subject: string): $CancellablePromise<$models.PurgeResult> {
    return $Call.ByID(321277507, name, keep, upToSeq, subject);
}

/**
 * RemoveStreamMessage deletes one message from a stream (safe erase —
 * noErase=false, data overwritten). Binds as "RemoveStreamMessage" because
 * jsm.Manager already exposes a same-named method this service would
 * otherwise collide with at the binding layer.
 */
export function RemoveStreamMessage(stream: string, seq: number): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(478388371, stream, seq);
}

export function ResetConsumer(stream: string, name: string, toSeq: number): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(2837509387, stream, name, toSeq);
}

export function RestoreBackup(dir: string, overwrite: boolean): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(2200918224, dir, overwrite);
}

export function ResumeConsumer(stream: string, name: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(2789968567, stream, name);
}

export function SealStream(name: string): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(475763909, name);
}

export function UpdateConsumer(form: $models.ConsumerForm): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(308510449, form);
}

export function UpdateStream(form: $models.StreamForm): $CancellablePromise<$models.CallResult> {
    return $Call.ByID(2714303341, form);
}
