// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BrowserMsg {
    "seq": number;
    "subject": string;
    "headers": { [_ in string]?: string[] };
    "payload_b64": string;
    "payload_size": number;
    "timestamp_ms": number;
    "is_utf8": boolean;

    /**
     * Truncated=true 时 PayloadB64 仅携带前 64KB（行级预览上限），
     * PayloadSize 仍为完整大小；完整内容经 GetStreamMessage / 下载获取。
     * 防止大消息页（如 50×2MB）把单页载荷推到百 MB 级（§6.6「仅展示
     * 元数据与十六进制预览」的 wire 半边）。
     */
    "truncated": boolean;

    /** Creates a new BrowserMsg instance. */
    constructor($$source: Partial<BrowserMsg> = {}) {
        if (!("seq" in $$source)) {
            this["seq"] = 0;
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }
        if (!("payload_b64" in $$source)) {
            this["payload_b64"] = "";
        }
        if (!("payload_size" in $$source)) {
            this["payload_size"] = 0;
        }
        if (!("timestamp_ms" in $$source)) {
            this["timestamp_ms"] = 0;
        }
        if (!("is_utf8" in $$source)) {
            this["is_utf8"] = false;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserMsg instance from a string or object.
     */
    static createFrom($$source: any = {}): BrowserMsg {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField2_0($$parsedSource["headers"]);
        }
        return new BrowserMsg($$parsedSource as Partial<BrowserMsg>);
    }
}

export class BrowserPageRequest {
    "stream": string;

    /**
     * 页首序列（含）
     */
    "start_seq": number;

    /**
     * 20/50/100/200
     */
    "count": number;

    /**
     * 可选；非空时前端禁用"上一页"
     */
    "subject_filter": string;

    /** Creates a new BrowserPageRequest instance. */
    constructor($$source: Partial<BrowserPageRequest> = {}) {
        if (!("stream" in $$source)) {
            this["stream"] = "";
        }
        if (!("start_seq" in $$source)) {
            this["start_seq"] = 0;
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("subject_filter" in $$source)) {
            this["subject_filter"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserPageRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BrowserPageRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrowserPageRequest($$parsedSource as Partial<BrowserPageRequest>);
    }
}

export class BrowserPageResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;
    "messages": BrowserMsg[];

    /**
     * 下一页请求起点（最后一条 seq+1；空页 = StartSeq）
     */
    "next_start_seq": number;
    "has_more": boolean;

    /** Creates a new BrowserPageResult instance. */
    constructor($$source: Partial<BrowserPageResult> = {}) {
        if (!("error_code" in $$source)) {
            this["error_code"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("next_start_seq" in $$source)) {
            this["next_start_seq"] = 0;
        }
        if (!("has_more" in $$source)) {
            this["has_more"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserPageResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BrowserPageResult {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField2_0($$parsedSource["messages"]);
        }
        return new BrowserPageResult($$parsedSource as Partial<BrowserPageResult>);
    }
}

/**
 * CallResult is embedded in every bound-call result; Ok is true iff
 * ErrorCode is empty.
 */
export class CallResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;

    /** Creates a new CallResult instance. */
    constructor($$source: Partial<CallResult> = {}) {
        if (!("error_code" in $$source)) {
            this["error_code"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CallResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CallResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CallResult($$parsedSource as Partial<CallResult>);
    }
}

export class ClusterOut {
    "name": string;
    "raft_group": string;
    "leader": string;

    /**
     * 0 = unknown
     */
    "leader_since_ms": number;
    "peers": PeerOut[];

    /** Creates a new ClusterOut instance. */
    constructor($$source: Partial<ClusterOut> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("raft_group" in $$source)) {
            this["raft_group"] = "";
        }
        if (!("leader" in $$source)) {
            this["leader"] = "";
        }
        if (!("leader_since_ms" in $$source)) {
            this["leader_since_ms"] = 0;
        }
        if (!("peers" in $$source)) {
            this["peers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterOut instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterOut {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("peers" in $$parsedSource) {
            $$parsedSource["peers"] = $$createField4_0($$parsedSource["peers"]);
        }
        return new ClusterOut($$parsedSource as Partial<ClusterOut>);
    }
}

export class GetMsgResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;
    "msg": BrowserMsg | null;

    /** Creates a new GetMsgResult instance. */
    constructor($$source: Partial<GetMsgResult> = {}) {
        if (!("error_code" in $$source)) {
            this["error_code"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("msg" in $$source)) {
            this["msg"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetMsgResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GetMsgResult {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("msg" in $$parsedSource) {
            $$parsedSource["msg"] = $$createField2_0($$parsedSource["msg"]);
        }
        return new GetMsgResult($$parsedSource as Partial<GetMsgResult>);
    }
}

export class ListStreamsResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;

    /**
     * 失败时 nil
     */
    "streams": StreamSummary[];

    /**
     * 非空 → 前端渲染指引面板
     */
    "unavailable_reason": string;

    /** Creates a new ListStreamsResult instance. */
    constructor($$source: Partial<ListStreamsResult> = {}) {
        if (!("error_code" in $$source)) {
            this["error_code"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("streams" in $$source)) {
            this["streams"] = [];
        }
        if (!("unavailable_reason" in $$source)) {
            this["unavailable_reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListStreamsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ListStreamsResult {
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("streams" in $$parsedSource) {
            $$parsedSource["streams"] = $$createField2_0($$parsedSource["streams"]);
        }
        return new ListStreamsResult($$parsedSource as Partial<ListStreamsResult>);
    }
}

export class PeerOut {
    "name": string;
    "current": boolean;
    "offline": boolean;
    "active_ms": number;
    "lag": number;

    /** Creates a new PeerOut instance. */
    constructor($$source: Partial<PeerOut> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = false;
        }
        if (!("offline" in $$source)) {
            this["offline"] = false;
        }
        if (!("active_ms" in $$source)) {
            this["active_ms"] = 0;
        }
        if (!("lag" in $$source)) {
            this["lag"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PeerOut instance from a string or object.
     */
    static createFrom($$source: any = {}): PeerOut {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PeerOut($$parsedSource as Partial<PeerOut>);
    }
}

export class PurgeResult {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;
    "purged": number;

    /** Creates a new PurgeResult instance. */
    constructor($$source: Partial<PurgeResult> = {}) {
        if (!("error_code" in $$source)) {
            this["error_code"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("purged" in $$source)) {
            this["purged"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PurgeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PurgeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PurgeResult($$parsedSource as Partial<PurgeResult>);
    }
}

export class SourceInfo {
    "name": string;
    "lag": number;

    /**
     * -1 = 无活动（jsm 语义映射）
     */
    "active_ms": number;
    "filter_subject": string;
    "opt_start_seq": number;
    "error"?: string;

    /** Creates a new SourceInfo instance. */
    constructor($$source: Partial<SourceInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("lag" in $$source)) {
            this["lag"] = 0;
        }
        if (!("active_ms" in $$source)) {
            this["active_ms"] = 0;
        }
        if (!("filter_subject" in $$source)) {
            this["filter_subject"] = "";
        }
        if (!("opt_start_seq" in $$source)) {
            this["opt_start_seq"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SourceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceInfo($$parsedSource as Partial<SourceInfo>);
    }
}

export class StreamDetail {
    "error_code": string;

    /**
     * server原文 for server/validation errors
     */
    "error": string;
    "summary": StreamSummary;

    /**
     * 编辑/复制的表单回显
     */
    "form": StreamForm;
    "created_ms": number;
    "state": StreamStateOut;
    "mirror": SourceInfo | null;
    "sources": SourceInfo[];
    "cluster": ClusterOut | null;

    /** Creates a new StreamDetail instance. */
    constructor($$source: Partial<StreamDetail> = {}) {
        if (!("error_code" in $$source)) {
            this["error_code"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = (new StreamSummary());
        }
        if (!("form" in $$source)) {
            this["form"] = (new StreamForm());
        }
        if (!("created_ms" in $$source)) {
            this["created_ms"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = (new StreamStateOut());
        }
        if (!("mirror" in $$source)) {
            this["mirror"] = null;
        }
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamDetail {
        const $$createField2_0 = $$createType7;
        const $$createField3_0 = $$createType9;
        const $$createField5_0 = $$createType10;
        const $$createField6_0 = $$createType12;
        const $$createField7_0 = $$createType13;
        const $$createField8_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField2_0($$parsedSource["summary"]);
        }
        if ("form" in $$parsedSource) {
            $$parsedSource["form"] = $$createField3_0($$parsedSource["form"]);
        }
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField5_0($$parsedSource["state"]);
        }
        if ("mirror" in $$parsedSource) {
            $$parsedSource["mirror"] = $$createField6_0($$parsedSource["mirror"]);
        }
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField7_0($$parsedSource["sources"]);
        }
        if ("cluster" in $$parsedSource) {
            $$parsedSource["cluster"] = $$createField8_0($$parsedSource["cluster"]);
        }
        return new StreamDetail($$parsedSource as Partial<StreamDetail>);
    }
}

/**
 * StreamForm: 数值字段 0 = 不设置（服务器默认），-1 = 无限制（max_age_seconds 除外，仅 ≥0）。
 */
export class StreamForm {
    "name": string;
    "description": string;
    "subjects": string[];

    /**
     * file | memory
     */
    "storage": string;

    /**
     * limits | interest | workqueue
     */
    "retention": string;
    "max_msgs": number;
    "max_bytes": number;
    "max_age_seconds": number;
    "max_msgs_per_subject": number;

    /**
     * 1–5，0 视为 1
     */
    "replicas": number;
    "placement_cluster": string;
    "placement_tags": string[];
    "mirror": StreamSourceForm | null;
    "sources": StreamSourceForm[];

    /** Creates a new StreamForm instance. */
    constructor($$source: Partial<StreamForm> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("subjects" in $$source)) {
            this["subjects"] = [];
        }
        if (!("storage" in $$source)) {
            this["storage"] = "";
        }
        if (!("retention" in $$source)) {
            this["retention"] = "";
        }
        if (!("max_msgs" in $$source)) {
            this["max_msgs"] = 0;
        }
        if (!("max_bytes" in $$source)) {
            this["max_bytes"] = 0;
        }
        if (!("max_age_seconds" in $$source)) {
            this["max_age_seconds"] = 0;
        }
        if (!("max_msgs_per_subject" in $$source)) {
            this["max_msgs_per_subject"] = 0;
        }
        if (!("replicas" in $$source)) {
            this["replicas"] = 0;
        }
        if (!("placement_cluster" in $$source)) {
            this["placement_cluster"] = "";
        }
        if (!("placement_tags" in $$source)) {
            this["placement_tags"] = [];
        }
        if (!("mirror" in $$source)) {
            this["mirror"] = null;
        }
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamForm instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamForm {
        const $$createField2_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        const $$createField12_0 = $$createType17;
        const $$createField13_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subjects" in $$parsedSource) {
            $$parsedSource["subjects"] = $$createField2_0($$parsedSource["subjects"]);
        }
        if ("placement_tags" in $$parsedSource) {
            $$parsedSource["placement_tags"] = $$createField11_0($$parsedSource["placement_tags"]);
        }
        if ("mirror" in $$parsedSource) {
            $$parsedSource["mirror"] = $$createField12_0($$parsedSource["mirror"]);
        }
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField13_0($$parsedSource["sources"]);
        }
        return new StreamForm($$parsedSource as Partial<StreamForm>);
    }
}

export class StreamSourceForm {
    "name": string;
    "filter_subject": string;
    "opt_start_seq": number;

    /** Creates a new StreamSourceForm instance. */
    constructor($$source: Partial<StreamSourceForm> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("filter_subject" in $$source)) {
            this["filter_subject"] = "";
        }
        if (!("opt_start_seq" in $$source)) {
            this["opt_start_seq"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamSourceForm instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamSourceForm {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamSourceForm($$parsedSource as Partial<StreamSourceForm>);
    }
}

export class StreamStateOut {
    "first_time_ms": number;
    "last_time_ms": number;
    "num_subjects": number;

    /** Creates a new StreamStateOut instance. */
    constructor($$source: Partial<StreamStateOut> = {}) {
        if (!("first_time_ms" in $$source)) {
            this["first_time_ms"] = 0;
        }
        if (!("last_time_ms" in $$source)) {
            this["last_time_ms"] = 0;
        }
        if (!("num_subjects" in $$source)) {
            this["num_subjects"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamStateOut instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamStateOut {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamStateOut($$parsedSource as Partial<StreamStateOut>);
    }
}

export class StreamSummary {
    "name": string;
    "description": string;

    /**
     * "" | "kv" | "object" (KV_/O_ 前缀)
     */
    "internal_kind": string;
    "subjects": string[];

    /**
     * file | memory
     */
    "storage": string;

    /**
     * limits | interest | workqueue
     */
    "retention": string;
    "messages": number;
    "bytes": number;
    "consumers": number;
    "first_seq": number;
    "last_seq": number;
    "last_time_ms": number;
    "lost_msgs": number;
    "lost_bytes": number;
    "num_deleted": number;
    "is_mirror": boolean;
    "is_source": boolean;
    "leader_missing": boolean;
    "unhealthy_replicas": number;
    "replica_count": number;

    /** Creates a new StreamSummary instance. */
    constructor($$source: Partial<StreamSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("internal_kind" in $$source)) {
            this["internal_kind"] = "";
        }
        if (!("subjects" in $$source)) {
            this["subjects"] = [];
        }
        if (!("storage" in $$source)) {
            this["storage"] = "";
        }
        if (!("retention" in $$source)) {
            this["retention"] = "";
        }
        if (!("messages" in $$source)) {
            this["messages"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("consumers" in $$source)) {
            this["consumers"] = 0;
        }
        if (!("first_seq" in $$source)) {
            this["first_seq"] = 0;
        }
        if (!("last_seq" in $$source)) {
            this["last_seq"] = 0;
        }
        if (!("last_time_ms" in $$source)) {
            this["last_time_ms"] = 0;
        }
        if (!("lost_msgs" in $$source)) {
            this["lost_msgs"] = 0;
        }
        if (!("lost_bytes" in $$source)) {
            this["lost_bytes"] = 0;
        }
        if (!("num_deleted" in $$source)) {
            this["num_deleted"] = 0;
        }
        if (!("is_mirror" in $$source)) {
            this["is_mirror"] = false;
        }
        if (!("is_source" in $$source)) {
            this["is_source"] = false;
        }
        if (!("leader_missing" in $$source)) {
            this["leader_missing"] = false;
        }
        if (!("unhealthy_replicas" in $$source)) {
            this["unhealthy_replicas"] = 0;
        }
        if (!("replica_count" in $$source)) {
            this["replica_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamSummary {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subjects" in $$parsedSource) {
            $$parsedSource["subjects"] = $$createField3_0($$parsedSource["subjects"]);
        }
        return new StreamSummary($$parsedSource as Partial<StreamSummary>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = BrowserMsg.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = PeerOut.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Nullable($$createType2);
const $$createType7 = StreamSummary.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = StreamForm.createFrom;
const $$createType10 = StreamStateOut.createFrom;
const $$createType11 = SourceInfo.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($$createType11);
const $$createType14 = ClusterOut.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = StreamSourceForm.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $Create.Array($$createType16);
