// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Appearance {
    /**
     * light | dark | system
     */
    "theme": string;

    /**
     * en | zh-CN
     */
    "language": string;
}

export interface Behavior {
    "poll_interval_seconds": number;
    "request_timeout_seconds": number;

    /**
     * standard | relaxed
     */
    "confirm_level": string;
    "session_push_batching": boolean;
    "session_buffer_size": number;

    /**
     * debug|info|warn|error
     */
    "log_level": string;
}

export interface Privacy {
    "crash_reports": boolean;
    "update_check": boolean;
}

export interface Settings {
    "appearance": Appearance;
    "behavior": Behavior;
    "privacy": Privacy;
    "last_active_context": string;
}
